# ================================================================
# prj.conf — Zephyr + WAMR UART Runtime
# ================================================================

# -- Console et logs --------------------------------------------
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# -- UART (réception du .wasm par liaison série) ----------------
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# -- Mémoire ----------------------------------------------------
# Stack main : 8 Ko suffisent sans réseau
CONFIG_MAIN_STACK_SIZE=8192
# Heap Zephyr : 128 Ko pour WAMR (réduit depuis 256 Ko)
CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# -- malloc/free pour WAMR (pool interne) -----------------------
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=32768